---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-nginxapp-sot
  namespace: nginxflux
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/himansu88/nginxSOT.git
