---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginxsot
  namespace: nginxflux
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/himansu88/nginxsot.git
